# Generated by Django 4.2.7 on 2023-11-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Image',
        ),
    ]
