# Generated by Django 4.2.7 on 2023-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Recipes', '0002_rename_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
