# Generated by Django 4.2.7 on 2023-11-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Recipes', '0009_non_veg'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
