# Generated by Django 4.2.7 on 2023-11-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Recipes', '0010_breakfast_details_alter_breakfast_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast_details',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
