# Generated by Django 4.2.7 on 2023-12-02 07:57

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Recipes', '0013_dinner_details_delete_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='breakfast',
        ),
        migrations.DeleteModel(
            name='dinner',
        ),
        migrations.DeleteModel(
            name='juice',
        ),
        migrations.DeleteModel(
            name='non_veg',
        ),
        migrations.DeleteModel(
            name='sweet',
        ),
        migrations.DeleteModel(
            name='veg',
        ),
        migrations.AddField(
            model_name='breakfast_details',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
