# Generated by Django 4.2.7 on 2023-12-02 13:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Recipes', '0014_delete_breakfast_delete_dinner_delete_juice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast_details',
            name='video_url',
        ),
        migrations.AddField(
            model_name='breakfast_details',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=2),
            preserve_default=False,
        ),
    ]
