# Generated by Django 4.2.7 on 2023-12-03 07:03

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Recipes', '0015_remove_breakfast_details_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='juice_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AddField(
            model_name='dinner_details',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=2),
            preserve_default=False,
        ),
    ]
